### ISSUE TITLE
[feature] Print gitea URL at the end of the installation

### ISSUE THREAD

**Issue by alfsuse** [fuseml/fuseml#101]
It would be useful for the end-user to get some URL's  once the installation process is finished so that one knows immediately where to start working. 
I am thinking at:
- gitea URL (with the default user/pass?)
- MLFlow URL
- (optional) Tekton URL

**Comment by jsuchome** [comment]
![image](https://user-images.githubusercontent.com/910000/119516473-140baf00-bd77-11eb-8a3a-e27704d482e9.png)

@alfsuse what about this? Or do you want to summary of urls at the end, rather than during the deployment?
