### ISSUE TITLE
[Epic] Inference Engines - NVIDIA Triton Inference Engine

### ISSUE THREAD

**Issue by alfsuse** [fuseml/fuseml#152]
We should aim to have multiple inference engines supported to offer MLOps a rich option in terms of support. As a starter, we should target the most used ones.

Triton Inference Server provides a cloud and edge inferencing solution optimized for both CPUs and GPUs. Triton supports an HTTP/REST and GRPC protocol that allows remote clients to request inferencing for any model being managed by the server. For edge deployments, Triton is available as a shared library with a C API that allows the full functionality of Triton to be included directly in an application.

https://github.com/triton-inference-server/server

**Comment by stefannica** [comment]
KFServing already supports Triton as an inference service. We need to research the pros/cons of using Triton directly.

**Comment by stefannica** [comment]
Q: do we need to add Seldon Core support for Triton in V3 ?
A: not a priority, but if it fits, it would be nice to have

**Comment by stefannica** [comment]
Done in [v3](https://github.com/fuseml/fuseml/releases/tag/v0.3.0): KServe & Seldon Core Triton protocol support in the workflow predictor steps
