### ISSUE TITLE
[Epic] Inference Engines - Intel

### ISSUE THREAD

**Issue by alfsuse** [fuseml/fuseml#153]
We should aim to have multiple inference engines supported to offer MLOps a rich option in terms of support. As a starter, we should target the most used ones.

Inference Engine is a set of C++ libraries providing a common API to deliver inference solutions on the platform of your choice: CPU, GPU, or VPU. Use the Inference Engine API to read the Intermediate Representation, set the input and output formats, and execute the model on devices. While the C++ libraries is the primary implementation, C libraries and Python bindings are also available.

https://github.com/openvinotoolkit/openvino

**Comment by stefannica** [comment]
TBD: can we leverage other serving platforms (e.g. KFServing/Seldon core) to already cover the Intel Inference Engine ?

**Comment by stefannica** [comment]
Done in v3, see [release notes](https://github.com/fuseml/fuseml/releases/tag/v0.3.0)
