### ISSUE TITLE
E2e MLFlow use-case: don't rebuild container images if content doesn't change

### ISSUE THREAD

**Issue by stefannica** [fuseml/fuseml#162]
In the end-to-end workflow tutorial used as our current example, the container image used as a runtime environment for training the MLFlow model is re-built every time a codeset update is published. This is time consuming and only necessary if the conda.yaml requirements change. We should devise a way to allow the step (re)building the environment to be skipped and allow the training step to reuse the container image matching the current code contents.

It's not clear yet whether this only requires modifying the MLFlow extension, or the workflow built-in features, or both.

**Comment by flaviodsr** [comment]
A simple way to implement this would be to parse the requirements from the conda file, make a hash based on it and use that hash as the image tag. With that, when the pipeline is executed a task would build that tag, check if the image:tag already exists on the registry, if not build it, else skip building.
