### ISSUE TITLE
Update 3rd party tools to latest version

### ISSUE THREAD

**Issue by stefannica** [fuseml/fuseml#167]
We should use the latest version for the 3rd party tools that we install with the FuseML installer, or depend on for end-to-end demos, CI, etc:
* Tekton
* KFServing 
* KNative (+dependencies)
* MLFlow
* Gitea
* docker-registry (if updates are available)

**Comment by flaviodsr** [comment]
Tekton was covered in: https://github.com/fuseml/fuseml/pull/172
