### ISSUE TITLE
installer: rerunning the installer with extensions option fails

### ISSUE THREAD

**Issue by flaviodsr** [fuseml/fuseml#184]
Trying to install an extension after installing the `mlflow` one fails with the following error:
```
error installing FuseML: Failed to install extension mlflow: failed to install helm package from https://github.com/fuseml/extensions/raw/main/charts/mlflow-0.0.1.tgz: Failed installing mlflow chart: Error: cannot re-use a name that is still in use
```
Seems like the installer is not able to identify that the `mlflow` extension was already installed and tries to install it again.

**Comment by jsuchome** [comment]
Yeah, for this we need the extension registry...

**Comment by jsuchome** [comment]
For the case of helm charts though ... we could add some logic to check if the helm chart is already there ... we have it on other places
