### ISSUE TITLE
installer: uninstall skips `mlflow` and gets stuck at `knative` extension

### ISSUE THREAD

**Issue by flaviodsr** [fuseml/fuseml#185]
After successfully installing fuseml with all available extensions (`--extensions mlflow,cert-manager,knative,kfserving`) and running the example workflow, trying to uninstall it results in it skipping the `mlflow` extension and then getting stuck when trying to uninstall the `knative` extension.

```bash
❯ ./dist/fuseml-installer uninstall --extensions mlflow,cert-manager,knative,kfserving

Configuration...
  🧭  extension_repository: https://raw.githubusercontent.com/fuseml/extensions/main/installer/

🚢 Processing extension 'mlflow'...

🕞   Removing helm release mlflow .

⚠️  mlflow helm release not found, skipping.


🚢 Processing extension 'cert-manager'...

🚢 Processing extension 'knative'...

```

**Comment by jsuchome** [comment]
This might fix your problems https://github.com/fuseml/extensions/pull/14

**Comment by jsuchome** [comment]
1. uninstalling extension should not remove default namespace
2. --ignore-not-found needs to be passed to kustomize type too

**Comment by stefannica** [comment]
The MLFlow extension problem is fixed. Tracking the other one with https://github.com/fuseml/fuseml/issues/299
