### ISSUE TITLE
fuseml-installer (re-run to incrementally move on)

### ISSUE THREAD

**Issue by bwgartner** [fuseml/fuseml#206]
Have a repeated issue of hitting "429 Too Many Requests - Server message: toomanyrequests: You have reached your pull rate limit." during deployments.

🚢 FuseML installing...

Configuration...
  🧭  system_domain: 

🚢 Deploying Istio.....
✔️  Istio deployed
.
✔️  Created system_domain: 10.156.217.10.omg.howdoi.website

🚢 Deploying Quarks..............
✔️  Quarks deployed

🚢 Deploying Workloads...
✔️  Workloads deployed

🚢 Deploying MLflow.....error installing FuseML: Failed installing MLflow: Error: failed post-install: timed out waiting for the condition

( initial runs has this issue in istio space, but recent ones, after an uninstall/install cycle affected were mlflow-minio-make-bucket-job and mlflow-minio pods )

So just hoping a re-run of installer to increment beyond that ...

# fuseml-installer install

🚢 FuseML installing...

Configuration...
  🧭  system_domain: 

⚠️  Istio already installed, skipping ...
.
✔️  Created system_domain: 10.156.217.10.omg.howdoi.website

⚠️  Namespace quarks already present, skipping installation

⚠️  Namespace fuseml-workloads already present, skipping installation

🚢 Deploying MLflow.....error installing FuseML: Failed installing MLflow: Error: cannot re-use a name that is still in use

So seem to be hitting an idempotent check/phase that is not in place yet

**Comment by jsuchome** [comment]
HI @bwgartner , could you try again with current version (preferably from `main` branch)?
It has some new ways to install components (so called extensions) and also ways to detect potential installed parts.

It does not have an ability to repair e.g. failed helm chart installations, but I think it should log enough information at least to hint user what's wrong...

**Comment by stefannica** [comment]
Note that the installer now also supports passing a `--force-reinstall` flag that will attempt to reinstall everything.
