### ISSUE TITLE
[Epic] - FUSEML Contributing guidelines and Documentation

### ISSUE THREAD

**Issue by alfsuse** [fuseml/fuseml#22]
We should aim to have a contributing guideline that may help those who want to help to be quickly "enabled".
We should have a proposal, in the form of one or more issues to be approved and that will produce, as an outcome, a contributing.md file that implements this epic and its user-stories (the proposal above).

Also, we should set up a proper way to document the project through the Wiki's and/or other solutions like:
- readthedocs
- gitbooks

**Comment by evrardjp** [comment]
We probably have the framework now, should we close this and detail things in other cards ?
