### ISSUE TITLE
Create a CONTRIBUTING.MD file

### ISSUE THREAD

**Issue by alfsuse** [fuseml/fuseml#23]
This issue implements #22  Epic.

Many projects have a CONTRIBUTING.md file where they explain how a use may contribute to the project. This more a governance model that try to avoid unexpected and rogue behaviors within the project.
- GitHub as some samples (here)[https://github.com/github/docs/blob/main/CONTRIBUTING.md]
- KubeFlow (here)[https://github.com/kubeflow/community/blob/master/CONTRIBUTING.md]
We should define our own version. Here attached a sample we may use:

# How to Contribute
We'd love to accept your patches and contributions to this project. There are
just a few small guidelines you need to follow.

# Git
* Each bug/feature must have its own branch.
* You create  the branch locally (avoiding to fork the project)
* Don't push directly to the `master` branch
* The PR must be validated, don't merge your own code
* Squash the commits to one for each PR
* The PR must have the Jira reference
* You should sign the commits

# Recommand process

## Environment setup
 - Fork this project to your individual account.
 - Clone this project to your R&D environment, like ```git clone git@github.com:<username>/fuseml.git```
 - In your fuseml directory, configure upstream: ```git remote add upstream 'git@github.com:fuseml/fuseml.git'```
 - Don't push to upstream directly: ```git remote set-url --push upstream no_push```
 - Configure you name for this project: ```git config user.name "your name"```
 - Configure your email for this project: ```git config user.email "xxxx@suse.com"```

## Update commits from upstream
 - Fetch commits from upstream: ```git fetch upstream```
 - Merge to your repo: ```git merge upstream/master```, we recommend only merge upstream commits to your master branch, and merge your master branch to the branch which you want to update.

## Create pull request
 - Create a branch for your PR: ```git checkout -b <proposal>```
 - Modify the code you want.
 - Push to your repo: ```git push origin <proposal>```
 - In your repo, choose \<proposal\> branch, then create a pull request.
 - Fill in the pull request template and click "Create".

# Long tasks
In case your tasks require more days, please update your job on here each couple of days.
If possible split the tasks into different sub-tasks so all the team can check the progress.

**Comment by alfsuse** [comment]
@evrardjp would the above still compliant with the https://www.contributor-covenant.org/ in your opinion?

**Comment by evrardjp** [comment]
Small nits:
- The `git` section doesn't match the "Create PR" section.
- It's confusing to mention Jira without mentioning an url
- We can give other tips for contributions

Instead of commenting in here, do you mind if I push a PR, and we see how that goes in the reviews?

**Comment by evrardjp** [comment]
And yeah, we can make this compliant.
