### ISSUE TITLE
Create a CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by alfsuse** [fuseml/fuseml#24]
As for the CONTRIBUTING file we should have a Code of Conduct file to be sure everyone is:
- kind with each other users contributing to the project
- proactive to stop any violation to the above point
- be inclusive
A good sample is GitHub CoC sample (here)[https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md]

**Comment by evrardjp** [comment]
Similarly we could reuse the CNCF CoC.

**Comment by alefesta** [comment]
That's a brilliant idea ...researching from there I landed on https://www.contributor-covenant.org/ I think we could adopt it and use it exposing also the badge as they indicate.
If everyone else agree and we put a like on @evrardjp suggestion we may proceed and call the PR.

**Comment by alfsuse** [comment]
*re-issue using my contributor account for clarity*

That's a brilliant idea ...researching from there I landed on https://www.contributor-covenant.org/ I think we could adopt it and use it exposing also the badge as they indicate.
If everyone else agree and we put a like on @evrardjp suggestion we may proceed and call the PR.

**Comment by evrardjp** [comment]
yeah it's also a good one!
