### ISSUE TITLE
Remove limitation of having a single predictor (application) per codeset

### ISSUE THREAD

**Issue by stefannica** [fuseml/fuseml#266]
Deploying two or more prediction services from the same codeset is not currently possible. The following objects and resources have identifiers that are tied to the codeset name and project:
* the FuseML Application
* the specific CRD instances (e.g. seldon core, kfserving)
* the URL where the prediction service is running

**Comment by jsuchome** [comment]
Implemeted with https://github.com/fuseml/extensions/pull/59
