### ISSUE TITLE
failure when pushing image to registry: http2: response body closed

### ISSUE THREAD

**Issue by jsuchome** [fuseml/fuseml#27]
Sometimes the pipeline fails during the build-and-push step with this error coming from the pod

`[APP] step-build-and-push error pushing image: failed to push to destination registry.fuseml-registry/apps/mlflow-85042120: Patch "https://registry.fuseml-registry/v2/apps/mlflow-85042120/blobs/uploads/69499f5e-6cbf-47a2-8b0f-87e253d76e20?_state=_pqnsBy9rkd7HGyP4FF4IvnF22UB1DGU0c1ZZxjJlWx7Ik5hbWUiOiJhcHBzL21sZmxvdy04NTA0MjEyMCIsIlVVSUQiOiI2OTQ5OWY1ZS02Y2JmLTQ3YTItOGIwZi04N2UyNTNkNzZlMjAiLCJPZmZzZXQiOjAsIlN0YXJ0ZWRBdCI6IjIwMjEtMDMtMTdUMTQ6MjQ6NDkuNjc0NzQxODI0WiJ9": http2: response body closed .`

**Comment by stefannica** [comment]
Needs to be re-checked with the new server-side workflow/pipeline management

**Comment by stefannica** [comment]
Please re-open if this is still reproducible.
