### ISSUE TITLE
CLI should print more verbose information about workflow runs

### ISSUE THREAD

**Issue by jsuchome** [fuseml/fuseml#53]
After (or during) running a fuseml workflow, it could be nice to be able to retrieve more verbose information through the CLI about the state of the workflow and the specific artifacts that are created (e.g. S3 endpoints for generated models, serving URLs).

**Comment by stefannica** [comment]
Implemented by https://github.com/fuseml/fuseml-core/pull/34

**Comment by stefannica** [comment]
https://github.com/fuseml/fuseml-core/pull/67 also adds user-friendly formatting on top.

I think this can be closed @jsuchome .
