### ISSUE TITLE
Explore goa as a code generator for fuseml-core

### ISSUE THREAD

**Issue by stefannica** [fuseml/fuseml#55]
Goa (https://goa.design/learn/getting-started/) features code generation not only for REST APIs, but also for gRPC. This will be extremely useful in the context of detaching 3rd party tool specific code (e.g. artifact stores and workload agents) from the fuseml core service and running them as independent micro-services. Communication between the fuseml core service and its agents should be done using gRPC, and GOA gives us the option of generating the transport specific code stubs independent of the information being transported. Another advantage for using GOA is that it's compatible with newer openapi versions (3.0), whereas go-swagger, the current option being explored for fuseml-core, is stuck at 2.0 without any plans in sight to add support for 3.0.

Aspects to consider when exploring GOA to generate the REST/gRPC code stubs for fuseml-core:

- where else is goa used (what other projects are using goa successfully) ? does that compare to go-swagger ?
- how expressive is it ? does it provide more or less flexibility than go-swagger ?
- how easy is it to work with ? is there a learning curve that is comparable to that required to work with the openapi specification ?
- does it provide middleware features comparable or better than what is supported with go-swagger (e.g. support for integration with authentication and authorization frameworks such as OAuth and LDAP, logging, tracing etc.)

**Comment by flaviodsr** [comment]
An example of generating the API for the runnable component is available at: https://github.com/fuseml/fuseml-core

Regarding the aspects:
- I was not able to find any relevant project that uses Goa, I did search on google and github and mostly of the projects are small and personal projects.
- To describe the API Goa uses its own DSL which is basically Go (https://pkg.go.dev/goa.design/goa/v3/dsl) the documentation is nice and personally I think it is very simple to understand. There is also a repository with some examples (https://github.com/goadesign/examples).
- Goa provides a mechanism of plugins that can be used to extend the code generation, currently there are two plugins available: cors and goakit (https://github.com/goadesign/plugins).
- Goa also has built-in support for multiple security schemes: basic auth, API key (a.k.a. shared secret), JWT and OAuth2 (https://goa.design/design/security/)
