### ISSUE TITLE
Define data structures and interfaces for the codeset element

### ISSUE THREAD

**Issue by stefannica** [fuseml/fuseml#56]
As covered in the [wiki](https://github.com/fuseml/fuseml/wiki/Design-concepts), the codeset is the business logic element used to represent the machine learning application files (code, configuration, scripts, etc) created by data scientists during the ML experimentation phase and out of which the MLOps pipeline components are built and ultimately executed. 

The FuseML core service needs an internal representation of these codesets, as well as an interface defining the operations that it needs to perform on them (referred to as the codeset store) for the purpose of implementing other operational concepts such as runnables, pipeline templates and pipelines.

Ideally, the core code used to define the codeset element and operations should be designed as "business domain" code: independent of outer layer logic that deals with presentation, serialization, storage etc.

**Comment by jsuchome** [comment]
Identification of a codeset
 - name + commit id (saved as part of codeset struct)
 - together with data shared between multiple codesets, obtainable from Codeset Store

Codeset store
 - must store git repo URL, org, user and password
 - question is, if all codesets managed by fuseml codeset store must point to the same repository (probably not, but for simplicity we can assume they will)

API 
 - New
   - Inputs:
     - path to directory on a local filesystem (Does it make sense to consider non-local system?)
     - name (= repo name)
   - Output: ID (git commit ID)
 - Update/Modify (probably not necessary)
 - Get/Clone
   - Inputs:
     - name
     - (optionally) commit id - if not provided, return the latest
     - path to directory where it should be cloned (does it make sense to Get the object without requesting Clone?)
  - Delete

**Comment by jsuchome** [comment]
Now it might make sense to CodeSet to define Hook (that is pointing out to some pipeline engine so that it executes a pipeline when a modification of codeset is made). Hook is repository specific, so kind of makes sense to define it whenever new CodeSet is created

**Comment by stefannica** [comment]
> question is, if all codesets managed by fuseml codeset store must point to the same repository (probably not, but for simplicity we can assume they will)

@jsuchome If by repository you mean git repository, then I don't think we can assume that. Different users, or even the same user working on different ML applications will want to use a different git repository for every application. If by repository you mean git server, then yes, for simplicity, we can assume that all codesets will point to the internal gitea git server.

There's also the question of how git organizations fit into all this. I can imagine that users will want to group their code, pipelines and artifacts into higher level concepts, something like a project, and for codesets we could map that to a git organization.

**Comment by jsuchome** [comment]
Yeah, basically I'm trying to figure out which of the parts that identify a codeset are really the codeset attributes and which are the attributes saved in the codeset store, i.e. what is shared between all codesets.

It almost looks like we need another layer between the store (that only has git server as global variable/const) and final codeset, identified by git server, user, name, org, repository and commit id.

**Comment by jsuchome** [comment]
repository is basically "application". So of course I was wrong assuming all codesets share one. I think I had the git server in mind in this sentence.

**Comment by jsuchome** [comment]
Closed by https://github.com/fuseml/fuseml-core/pull/8
