### ISSUE TITLE
Purge old fuseml CLI code from installer

### ISSUE THREAD

**Issue by stefannica** [fuseml/fuseml#67]
With the new fuseml CLI in place, the old CLI inherited from carrier can be repurposed as an installer and all other code pertaining to pushing code to gitea, setting up webhooks, configuring pipelines and so on can be removed, and the binary renamed to reflect its new function.

**Comment by jsuchome** [comment]
I have started here https://github.com/fuseml/fuseml/pull/81 ... but then I realized there are still actions that can only be done by current fuseml code and not yet by fuseml-core so it seems finishing it now is too early.
So I think we need to keep it as WIP and continue once we have more functionality (most importantly, the pipelines) in the core package.
