### ISSUE TITLE
Feature: service registry

### ISSUE THREAD

**Issue by stefannica** [fuseml/fuseml#75]
We need to manage the services deployed by the pipelines (e.g. prediction services) as first class citizens in fuseml. This enables users to show/list/delete running services.

**Comment by stefannica** [comment]
Implementation variants, based on the online discussion we just had, related to how "services" are created and deleted, together with their associated k8s resources:
1. the "service" descriptor is provided as an extra output of the same container that creates the KFServing resource (e.g. a yaml file) and the workflow engine extracts that somehow and publishes the "service" in the store
2. use the k8s operator created by Flavio as the back-end that stores and manages "services" and model everything on top of it
3. reuse the same container that creates the KFServing resources to handle the deleting (and updating) operations. Execute it from the "service" store back-end the same as we execute it from the pipeline every time a delete operation is required
4. run a standalone service (or just standalone component in fuseml core) that is responsible not just for
storing "service" entries, but also for interacting with the "back-end" KFserving / seldon core etc. solution to create/delete/update concrete applications

alternative combining 1+3: update the container that creates the KFServing resources to also call the FuseML API and register the "service" and its k8s resources. The "service" store is responsible for deleting them.

**Comment by jsuchome** [comment]
I believe this is done now.
